# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aisles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle_id', models.IntegerField(blank=True, null=True)),
                ('aisle', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'aisles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instacart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=10, null=True)),
                ('product_id', models.CharField(blank=True, max_length=10, null=True)),
                ('add_to_cart_order', models.CharField(blank=True, max_length=10, null=True)),
                ('reordered', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'instacart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstacartPrior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=10, null=True)),
                ('product_id', models.CharField(blank=True, max_length=10, null=True)),
                ('add_to_cart_order', models.CharField(blank=True, max_length=10, null=True)),
                ('reordered', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'instacart_prior',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('eval_set', models.CharField(blank=True, max_length=10, null=True)),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('order_dow', models.IntegerField(blank=True, null=True)),
                ('order_hour_of_day', models.IntegerField(blank=True, null=True)),
                ('days_since_prior_order', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=30, null=True)),
                ('aisle_id', models.IntegerField(blank=True, null=True)),
                ('department_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('products', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'sample_submission',
                'managed': False,
            },
        ),
    ]
