# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Url_list_aready',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=200)),
                ('site_data', models.TextField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Url_list_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=200)),
                ('site_status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='site_info',
            name='site_url_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Url_list_aready'),
        ),
    ]
