# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_auto_20170719_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_list_aready',
            name='site_data',
            field=models.TextField(max_length=60000),
        ),
    ]
